### ISSUE TITLE
Using parameters in query with Retrofit

### ISSUE THREAD

**Issue by Barmaley74** [rameshvoltella/WoocommerceAndroidOAuth1#1]
Big thanks for your library!
I connect to my internet-store on WooCommerce using Retrofit - when I build simple queries such as "http://example.com/wp-json/wc/v1/products/categories" - all OK - passes authentication and I get a JSON result.
But if I try to use in query parameters such as "http://example.com/wp-json/wc/v1/products/categories?per_page=20" - I get an error 401 authorization.
You have never encountered such a problem?

**Comment by rameshvoltella** [comment]
@Barmaley74 i have encountered this issue i will update the code asap

**Comment by rameshvoltella** [comment]
@Barmaley74  i have updated the library.Please update the library and change the **OAuthInterceptor.class**

**Comment by rameshvoltella** [comment]
@Barmaley74 is the issue fixed for you?

**Comment by Barmaley74** [comment]
Yes, many thanks for your solution, all working good!!!
