### ISSUE TITLE
can you please specify location to place gradle dependency

### ISSUE THREAD

**Issue by ostwalankit** [rameshvoltella/WoocommerceAndroidOAuth1#6]
compile project(':woocommerseandroidoauth1library')

Placing this in app module dependency it gives error saying ,
Project with Path 'woocommerseandroidoauth1library' could not be found in project ':app'

help is appreciated. thank you!

**Comment by das-debdeep** [comment]
You need to add the woocommercelibrary as a library module. Then add the dependency.
